version: '2'
services:
  web:
    image: mon_projet_web
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data: